'use client';

import { useMemo } from 'react';
import { Check, Minus, RotateCcw } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { formatGoalDate } from '@/lib/goalDates';
import { useDeleteGoalCompletion, useDeleteShowUp, usePutGoalCompletion, usePutShowUp } from '@/lib/goalQueries';
import type { DateKey, Goal, GoalActivityStatus, GoalCompletion, ShowUp } from '@/types/goals';

interface Props { goal: Goal; date: DateKey | null; completions: GoalCompletion[]; showUps: ShowUp[]; onOpenChange: (open:boolean)=>void; onError:(message:string)=>void }
export default function DailyChecklistDialog({ goal,date,completions,showUps,onOpenChange,onError }:Props) {
  const putCompletion=usePutGoalCompletion(goal.id), deleteCompletion=useDeleteGoalCompletion(goal.id), putShowUp=usePutShowUp(goal.id), deleteShowUp=useDeleteShowUp(goal.id);
  const completionPending=putCompletion.isPending||deleteCompletion.isPending; const showUpPending=putShowUp.isPending||deleteShowUp.isPending;
  const rows=useMemo(()=>completions.filter((item)=>item.date===date),[completions,date]); const showUp=showUps.find((item)=>item.date===date);
  const complete=rows.filter((item)=>item.status==='complete').length; const progress=goal.subGoals.length?Math.round(complete/goal.subGoals.length*100):0;
  const attempt=async(task:()=>Promise<unknown>)=>{try{await task();}catch(e){onError(e instanceof Error?e.message:'Activity was not saved.');}};
  const setStatus=(subGoalId:string,status:'none'|GoalActivityStatus)=>{if(!date||completionPending)return;const current=rows.find((item)=>item.subGoalId===subGoalId);if(status==='none'){if(current)void attempt(()=>deleteCompletion.mutateAsync({subGoalId,date}));return;}void attempt(()=>putCompletion.mutateAsync({subGoalId,date,input:{status,source:'manual'}}));};
  return <Dialog open={Boolean(date)} onOpenChange={onOpenChange}><DialogContent className="bottom-0 top-auto max-h-[90dvh] w-full max-w-2xl translate-y-0 rounded-b-none sm:bottom-auto sm:top-1/2 sm:w-[calc(100%-2rem)] sm:-translate-y-1/2 sm:rounded-2xl">
    <DialogHeader><DialogTitle>{date?formatGoalDate(date):'Checklist'}</DialogTitle><DialogDescription>{goal.gridMode==='weekly'?'Weekly':'Daily'} checklist for {goal.title}</DialogDescription></DialogHeader>
    <div className="rounded-xl bg-ink/[0.035] p-3"><div className="flex items-center justify-between text-xs"><span className="font-medium text-ink">Checklist progress</span><span className="text-muted-ink">{complete}/{goal.subGoals.length} complete · {progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-ink/[0.08]"><div className="h-full origin-left bg-brand transition-transform motion-reduce:transition-none" style={{transform:`scaleX(${progress/100})`}} /></div></div>
    {goal.subGoals.length?<ul className="space-y-2">{goal.subGoals.map((subGoal)=>{const current=rows.find((item)=>item.subGoalId===subGoal.id);return <li key={subGoal.id} className="rounded-xl border border-hairline p-3"><p className="mb-2 text-sm font-medium text-ink">{subGoal.title}</p><div className="grid grid-cols-3 gap-1" role="group" aria-label={`${subGoal.title} status`}><StateButton disabled={completionPending} selected={!current} onClick={()=>setStatus(subGoal.id,'none')} label="Not done" /><StateButton disabled={completionPending} selected={current?.status==='partial'} onClick={()=>setStatus(subGoal.id,'partial')} label="Partial" icon={<Minus className="h-3.5 w-3.5" />} /><StateButton disabled={completionPending} selected={current?.status==='complete'} onClick={()=>setStatus(subGoal.id,'complete')} label="Complete" icon={<Check className="h-3.5 w-3.5" />} /></div></li>;})}</ul>:<p className="rounded-xl border border-dashed border-hairline p-5 text-center text-xs text-muted-ink">This goal has no checklist items. You can still mark a show-up manually.</p>}
    <section className="border-t border-hairline pt-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-ink">Show-up status</h3><p className="text-xs text-muted-ink">{showUp?`${showUp.status==='complete'?'Complete':'Partial'} · ${showUp.source==='manual'?'Marked by you':'From checklist'}`:'Not marked'}</p></div>{showUp?.source==='manual'&&date&&<button type="button" disabled={showUpPending} onClick={()=>void attempt(()=>deleteShowUp.mutateAsync(date))} className="press rounded-lg px-2 py-2 text-xs text-muted-ink"><RotateCcw className="mr-1 inline h-3.5 w-3.5" />Clear yours</button>}</div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={!date||showUpPending} onClick={()=>date&&void attempt(()=>putShowUp.mutateAsync({date,input:{status:'partial',source:'manual'}}))} className="press min-h-11 rounded-xl border border-warning text-xs font-medium text-ink"><Minus className="mr-1 inline h-4 w-4" />Mark partial</button><button type="button" disabled={!date||showUpPending} onClick={()=>date&&void attempt(()=>putShowUp.mutateAsync({date,input:{status:'complete',source:'manual'}}))} className="press min-h-11 rounded-xl bg-brand text-xs font-medium text-on-accent"><Check className="mr-1 inline h-4 w-4" />Mark complete</button></div><p className="mt-2 text-[10px] leading-4 text-muted-ink">Checklist changes let the server derive show-up status. A manual mark takes precedence until cleared.</p></section>
  </DialogContent></Dialog>;
}
function StateButton({selected,onClick,label,icon,disabled=false}:{selected:boolean;onClick:()=>void;label:string;icon?:React.ReactNode;disabled?:boolean}){return <button type="button" disabled={disabled} aria-pressed={selected} onClick={onClick} className={`press flex min-h-10 items-center justify-center gap-1 rounded-lg border text-[11px] disabled:opacity-40 ${selected?'border-brand bg-brand/10 text-ink':'border-hairline text-muted-ink'}`}>{icon}{label}</button>;}
