'use client';

import { Flame, Gauge, Trophy, UserCheck } from 'lucide-react';
import type { GoalGridMode, GoalStats } from '@/types/goals';

export default function MomentumStats({ stats, loading, cadence }: { stats?:GoalStats; loading:boolean; cadence:GoalGridMode }) {
  if(loading)return <div className="grid grid-cols-2 gap-2 lg:grid-cols-4" aria-label="Loading momentum">{[0,1,2,3].map(x=><div key={x} className="h-24 animate-pulse rounded-2xl bg-ink/[0.035] motion-reduce:animate-none" />)}</div>;
  const cards=[{label:'Momentum',value:`${stats?.momentum??0}%`,icon:Gauge},{label:'Current streak',value:String(stats?.currentStreak??0),icon:Flame},{label:'Best streak',value:String(stats?.bestStreak??0),icon:Trophy},{label:'Show-ups',value:String(stats?.showUps.total??0),icon:UserCheck}];
  return <><div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{cards.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-hairline bg-surface p-4"><Icon className="h-4 w-4 text-brand" /><p className="mt-3 text-2xl font-semibold tracking-tight text-ink">{value}</p><p className="text-[11px] text-muted-ink">{label}</p></div>)}</div><section className="mt-3 rounded-2xl border border-hairline bg-surface p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-ink">Weekday pattern</h2><span className="text-[10px] text-muted-ink">{cadence==='weekly'?'Weekly activity is anchored on Monday':'Complete + half credit for partial'}</span></div><ul className="mt-4 grid grid-cols-7 gap-2">{(stats?.weekdayPattern??[]).map((day)=><li key={day.weekday} className="text-center"><div className="mx-auto flex h-20 w-4 items-end overflow-hidden rounded-full bg-ink/[0.06]" aria-hidden="true"><div className="h-full w-full origin-bottom rounded-full bg-brand transition-transform duration-300 motion-reduce:transition-none" style={{transform:`scaleY(${day.completionRate/100})`}} /></div><span className="mt-1 block text-[10px] text-muted-ink">{day.weekday.slice(0,2)}</span><span className="block text-[10px] font-medium text-ink">{day.completionRate}%</span></li>)}</ul><p className="sr-only">{(stats?.weekdayPattern??[]).map(day=>`${day.weekday} ${day.completionRate} percent`).join(', ')}</p></section></>;
}
